version: 3

aliases:
  ensembl: rat
  snpeff: Rnor_5.0.74

rnaseq:
  transcripts: ../rnaseq/ref-transcripts.gtf
  transcripts_mask: ../rnaseq/ref-transcripts-mask.gtf
  transcriptome_index:
    tophat: ../rnaseq/tophat/rn5_transcriptome.ver
