# Template for whole genome Illumina variant calling with GATK pipeline
---
details:
  - analysis: variant2
    genome_build: GRCh37
    # to do multi-sample variant calling, assign samples the same metadata / batch
    # metadata:
    #   batch: your-arbitrary-batch-name
    algorithm:
      aligner: bwa
      mark_duplicates: picard
      recalibrate: gatk
      realign: gatk
      variantcaller: gatk
      platform: illumina
      quality_format: Standard
      coverage_interval: genome
      coverage_depth: high
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
